apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  type: LoadBalancer
  selector:
    app: mytriotaskflaskapp
  ports:
    - name: http
      port: 80
      targetPort: 5000
