apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytriotasksql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytriotasksql
  template:
    metadata:
      labels:
        app: mytriotasksql
    spec:
      containers:
        - name: mytriotasksql
          image: chrisreeves1/mytriotasksql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: flask-db
          ports:
            - containerPort: 3306
